# Generated by Django 5.1 on 2025-01-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
